// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inventory.proto

// Protobuf Java Version: 3.25.1
package com.smartorder.inventory.grpc;

public final class InventoryProto {
  private InventoryProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_smartorder_inventory_grpc_StockRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_smartorder_inventory_grpc_StockRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_smartorder_inventory_grpc_StockResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_smartorder_inventory_grpc_StockResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017inventory.proto\022\035com.smartorder.invent" +
      "ory.grpc\"4\n\014StockRequest\022\022\n\nproduct_id\030\001" +
      " \001(\t\022\020\n\010quantity\030\002 \001(\005\"3\n\rStockResponse\022" +
      "\021\n\tavailable\030\001 \001(\010\022\017\n\007message\030\002 \001(\t2{\n\020I" +
      "nventoryService\022g\n\nCheckStock\022+.com.smar" +
      "torder.inventory.grpc.StockRequest\032,.com" +
      ".smartorder.inventory.grpc.StockResponse" +
      "B1\n\035com.smartorder.inventory.grpcB\016Inven" +
      "toryProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_smartorder_inventory_grpc_StockRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_smartorder_inventory_grpc_StockRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_smartorder_inventory_grpc_StockRequest_descriptor,
        new java.lang.String[] { "ProductId", "Quantity", });
    internal_static_com_smartorder_inventory_grpc_StockResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_smartorder_inventory_grpc_StockResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_smartorder_inventory_grpc_StockResponse_descriptor,
        new java.lang.String[] { "Available", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
