// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inventory.proto

// Protobuf Java Version: 3.25.1
package com.smartorder.inventory.grpc;

public interface StockResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.smartorder.inventory.grpc.StockResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool available = 1;</code>
   * @return The available.
   */
  boolean getAvailable();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
