server:
  port: 8081

grpc:
  server:
    port: 50052

spring:
  datasource:
    url: jdbc:h2:mem:inventorydb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

inventory:
  grpc:
    # SmartOrder DNS çözümlemesi için tam domain adı
    host: inventory-service.smartorder.local
    port: 50052

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    com.smartorder: DEBUG
