INSERT INTO PRODUCT (PRODUCT_ID, NAME, STOCK_QUANTITY) VALUES ('P100', 'Laptop', 25);
INSERT INTO PRODUCT (PRODUCT_ID, NAME, STOCK_QUANTITY) VALUES ('P101', 'Mouse', 100);
INSERT INTO PRODUCT (PRODUCT_ID, NAME, STOCK_QUANTITY) VALUES ('P102', 'Keyboard', 60);
INSERT INTO PRODUCT (PRODUCT_ID, NAME, STOCK_QUANTITY) VALUES ('P103', 'Monitor', 40);
INSERT INTO PRODUCT (PRODUCT_ID, NAME, STOCK_QUANTITY) VALUES ('P104', 'Headset', 75);
