server:
  address: 0.0.0.0
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:smartorderdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: boot-bfgwhvlm.c1.kafka-serverless.eu-north-1.amazonaws.com:9098
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: AWS_MSK_IAM
      sasl.jaas.config: software.amazon.msk.auth.iam.IAMLoginModule required;
      sasl.client.callback.handler.class: software.amazon.msk.auth.iam.IAMClientCallbackHandler

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 10
      acks: all
      linger-ms: 5
      max-in-flight-requests-per-connection: 5

    admin:
      auto-create: true  # ✅ topic yoksa otomatik oluştur


grpc:
  client:
    inventory-service:
      address: static://inventory-service.smartorder.local:50052
      negotiation-type: plaintext
    payment-service:
      address: static://payment-service.smartorder.local:50051
      negotiation-type: plaintext

inventory:
  host: inventory-service.smartorder.local
  port: 50052

payment:
  host: payment-svc1.smartorder.local
  port: 50051

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    com.smartorder: DEBUG
    org.springframework.kafka: WARN
